### PR TITLE
Nd test

### PR DESCRIPTION
**Pull request by xialuoke4062**
## Checklist

- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by j1c** [comment]
- Nice work. 
- My main feedback is the same as Ryan's. Make a notebook that demonstrates your 3D version of otsu using an example 3D image. It can be from mouselight or whatever data you choose. It can be very similar to this: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html#sphx-glr-auto-examples-segmentation-plot-niblack-sauvola-py

**Comment by xialuoke4062** [comment]
> * My main feedback is the same as Ryan's. Make a notebook that demonstrates your 3D version of otsu using an example 3D image. It can be from mouselight or whatever data you choose. It can be very similar to this: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html#sphx-glr-auto-examples-segmentation-plot-niblack-sauvola-py

Thank you! We have made similar notebooks creating such images (https://github.com/NeuroDataDesign/mouselit/blob/master/stanley/Mouselight%20Test/3D%20Rank%20Filter.ipynb) - the problem is that the 3D image needs to use some viewer like napari, and cannot be straight-forwardly demonstrated in the notebook.

**Comment by j1c** [comment]
> > * My main feedback is the same as Ryan's. Make a notebook that demonstrates your 3D version of otsu using an example 3D image. It can be from mouselight or whatever data you choose. It can be very similar to this: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html#sphx-glr-auto-examples-segmentation-plot-niblack-sauvola-py
> 
> Thank you! We have made similar notebooks creating such images (https://github.com/NeuroDataDesign/mouselit/blob/master/stanley/Mouselight%20Test/3D%20Rank%20Filter.ipynb) - the problem is that the 3D image needs to use some viewer like napari, and cannot be straight-forwardly demonstrated in the notebook.

You dont have to visualize the whole volume. Just need a pic of a slice of that volume comparing before and after like what you showed in class within a jupyter notebook.

**Comment by xialuoke4062** [comment]
> > > * My main feedback is the same as Ryan's. Make a notebook that demonstrates your 3D version of otsu using an example 3D image. It can be from mouselight or whatever data you choose. It can be very similar to this: https://scikit-image.org/docs/stable/auto_examples/segmentation/plot_niblack_sauvola.html#sphx-glr-auto-examples-segmentation-plot-niblack-sauvola-py
> > 
> > 
> > Thank you! We have made similar notebooks creating such images (https://github.com/NeuroDataDesign/mouselit/blob/master/stanley/Mouselight%20Test/3D%20Rank%20Filter.ipynb) - the problem is that the 3D image needs to use some viewer like napari, and cannot be straight-forwardly demonstrated in the notebook.
> 
> You dont have to visualize the whole volume. Just need a pic of a slice of that volume comparing before and after like what you showed in class within a jupyter notebook.

Great, already updated - should we put a link to the notebook in the pr, or include the notebook somewhere in the pr (and where?)

**Comment by j1c** [comment]
Put the notebook in mouselit repo

**Comment by xialuoke4062** [comment]
> Put the notebook in mouselit repo

It is in the mouselit repo: https://github.com/NeuroDataDesign/mouselit/blob/master/stanley/Mouselight%20Test/3D%20Rank%20Filter.ipynb

**Pull request merged**
