### PR TITLE
3D support for filters.rank.equalize

### PR DESCRIPTION
**Pull request by ryanlu41**
## Description
Added 3D support for filters.rank.equalize. I created a 3D traversal algorithm as well as frameworks for increased 3D support and testing with the module. 

This enhancement helps with https://github.com/scikit-image/scikit-image/issues/3955

Jupyter notebook with more tests and proof: https://github.com/NeuroDataDesign/mouselit/blob/master/ryan/3D%20Equalizer/Proof%20of%203D%20Equalization.ipynb

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Gallery example in `./doc/examples` (new features only)
- [x] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- [x] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- [x] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by ryanlu41** [comment]
Not sure why Travis tests are failing. If you click details, its not even my branch. If you look here: https://travis-ci.org/NeuroDataDesign/scikit-image/branches?utm_medium=notification&utm_source=github_status my branch passes the tests. Do you know how to fix this?

**Comment by j1c** [comment]
- This looks pretty good! Nice work.
- My main feedback is to make some demonstration notebook of histogram equalization in 3D. I know the notebook you link is for testing purposes, but a demo showing the 3d version applied to mouselight data with some simple visualizations? Or some trivial 3D images. Something very similar to sk-images 2d example: https://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_local_equalize.html#sphx-glr-auto-examples-color-exposure-plot-local-equalize-py. 

EDIT: I realize you added a line to that example py file I linked. But having an actual example that includes 3D image would be great.

**Comment by ryanlu41** [comment]
I can do that, the main reason why I didn't originally was because creating a static 3D visualization didn't seem to make sense/wouldn't look super good. Do you have any recommendations for that?

**Comment by j1c** [comment]
Honestly, what you did for the presentation is fine. Just an image of a slice (or two). But in a form of a notebook.

**Comment by ryanlu41** [comment]
@j1c I've added an example notebook, code to load the image, and tests for that code. 

The example notebook can be found here: https://github.com/NeuroDataDesign/mouselit/blob/master/ryan/Sk%20Image%20Tests/3D%20Histogram%20Equalization%20Demo.ipynb

I inserted this same demo into the documentation, so it creates this html:
https://htmlpreview.github.io/?https://github.com/NeuroDataDesign/mouselit/blob/master/ryan/Sk%20Image%20Tests/HTML%20Docs/html/auto_examples/color_exposure/plot_local_equalize.html

**Pull request merged**
